//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iamDeveloper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Specialty
    {
        public long ID { get; set; }
        public long IDUser { get; set; }
        public int IDSpeCategory { get; set; }
        public int IDAcountCategory { get; set; }
    
        public virtual tbl_AcountCategory tbl_AcountCategory { get; set; }
        public virtual tbl_SpeciflyCategory tbl_SpeciflyCategory { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
